### ISSUE TITLE
How did you get this

### ISSUE THREAD

**Issue by adk23333** [novel-rs/api#20]
[utils.rs](https://github.com/novel-rs/api/blob/294f0b3ddd7a1d426a4587744356220598cce1d1/src/sfacg/utils.rs#L20)

Lines 20 and 21

`
    const USERNAME: &str = "apiuser";
    const PASSWORD: &str = "3s#1-yt6e*Acv@qer";
`

This is' androiduser 'on my device

**Comment by TerakomariGandesblood** [comment]
> [utils.rs](https://github.com/novel-rs/api/blob/294f0b3ddd7a1d426a4587744356220598cce1d1/src/sfacg/utils.rs#L20)
> 
> Lines 20 and 21
> 
> `const USERNAME: &str = "apiuser"; const PASSWORD: &str = "3s#1-yt6e*Acv@qer";`
> 
> This is' androiduser 'on my device

Under iOS is the above value, under Android is androiduser and 1a#$51-yt69;*Acv@qxq
